#!/bin/sh

########################
SCRIPT=`readlink -f $0`
SCRIPTPATH=`dirname $SCRIPT`

CONFIGPATH=$HOME/.config
########################
COMPTON_CONF=compton.conf
OPENBOX_DIR=openbox
OPENBOX_AUTOSTART=$OPENBOX_DIR/autostart
OPENBOX_RC=$OPENBOX_DIR/rc.xml
OPENBOX_MENU=$OPENBOX_DIR/menu.xml
CONKY_CONF=conkyrc
TERMINATOR_DIR=terminator
TERMINATOR_CONF=$TERMINATOR_DIR/config
TINT2_DIR=tint2
TINT2_CONF=$TINT2_DIR/tint2rc
GSIMPLECAL_DIR=gsimplecal
GSIMPLECAL_CONF=$GSIMPLECAL_DIR/config

########################

ln -sf $SCRIPTPATH/$COMPTON_CONF $CONFIGPATH/$COMPTON_CONF

mkdir -p $CONFIGPATH/$OPENBOX_DIR
ln -sf $SCRIPTPATH/$OPENBOX_AUTOSTART $CONFIGPATH/$OPENBOX_AUTOSTART
ln -sf $SCRIPTPATH/$OPENBOX_RC $CONFIGPATH/$OPENBOX_RC
ln -sf $SCRIPTPATH/$OPENBOX_MENU $CONFIGPATH/$OPENBOX_MENU

ln -sf $SCRIPTPATH/$CONKY_CONF $HOME/.$CONKY_CONF

mkdir -p $CONFIGPATH/$TERMINATOR_DIR
ln -sf $SCRIPTPATH/$TERMINATOR_CONF $CONFIGPATH/$TERMINATOR_CONF

mkdir -p $CONFIGPATH/$TINT2_DIR
ln -sf $SCRIPTPATH/$TINT2_CONF $CONFIGPATH/$TINT2_CONF

mkdir -p $CONFIGPATH/$GSIMPLECAL_DIR
ln -sf $SCRIPTPATH/$GSIMPLECAL_CONF $CONFIGPATH/$GSIMPLECAL_CONF

########################
